---
name:                      StartKit
main:                      blugin\startkit\StartKit
version:                   1.0.3
api:                       [3.0.0-ALPHA12]
author:                    PresentKim
website:                   https://github.com/Blugin/StartKit-PMMP
description:               A plugin give start kit to player

permissions:
  startkit.cmd:
    description:           StartKit command
    default:               op
...
